# Generated by Django 2.2.4 on 2021-07-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=7)),
                ('renovated', models.BooleanField()),
                ('air_conditioning', models.BooleanField()),
                ('pool', models.BooleanField()),
                ('allows_pets', models.BooleanField()),
                ('laundry_onsite', models.BooleanField()),
            ],
        ),
    ]
