# Generated by Django 2.2.4 on 2021-07-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210726_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apartment_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='contact_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
